# Hardware configuration for: Lenovo ThinkCentre M70q Gen 2
# Part number: 11N0S1AB00 | Board: Lenovo 31A7
# CPU: 11th Gen Intel Core i7-11700T (8c/16t, 1.4-4.6 GHz)
# RAM: 16 GB
# Storage: 477 GB NVMe (primary) + 233 GB SATA HDD
#
# Generated by 'nixos-generate-config' -- do not edit by hand.
# Machine-specific UUIDs and kernel modules are preserved verbatim.

{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/49f72dbb-d0cf-4c1c-8646-7fcf20e48ed0";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3B76-D99A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # No on-disk swap partition; swap is provided at runtime via zram
  # (configuration.nix: zramSwap.enable).
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
