# Hardware: LENOVO 11N0S1AB00.
#
# Generated by install.sh on 2026-06-15T20:09:06Z.
# Hand-edit freely; the installer won't overwrite an existing default.nix.

{ lib, ... }:

{
  imports = [ ../../nixos/disko-standard.nix ]
    ++ lib.optional (builtins.pathExists ./local.nix) ./local.nix;

  # Target disk for disko-standard.
  disko.devices.disk.main.device = lib.mkForce "/dev/nvme0n1";

  # facter.json overrides hardware-detection bits of hardware-configuration.nix.
  hardware.facter.reportPath =
    lib.mkIf (builtins.pathExists ./facter.json) ./facter.json;
}
