# nixos/modules/sysbox — sysbox-runc OCI runtime layered on the k3s base.
#
# Adds sysbox-runc as an additional containerd runtime so workspace pods can run
# with runtimeClassName: sysbox-runc and get unprivileged Docker-in-container
# support without privileged: true.
#
# Usage in configuration.nix (or the host's hosts/<host>/local.nix):
#   services.coder-nixos.sysbox.enable = true;
#
# Enabling this enables the k3s base (nixos/modules/k3s) automatically. Do NOT
# enable services.coder-nixos.podman at the same time — both expect to own pod
# scheduling.
#
# Packages:
#   sysbox-runc 0.7.0 — built from source (packages/sysbox-runc). 0.7.0 adds the
#     `features` subcommand containerd 2.x needs to report user_namespaces: true,
#     enabling hostUsers: false with runtimeClassName: sysbox-runc.
#   sysbox-mgr / sysbox-fs 0.6.7 — extracted from the CE .deb (packages/sysbox-ce).
#
# Apply: sudo nixos-rebuild switch

{ config, lib, pkgs, ... }:

let
  cfg = config.services.coder-nixos.sysbox;

  # See packages/sysbox-runc and packages/sysbox-ce for build details.
  sysboxRunc  = pkgs.callPackage ../../../packages/sysbox-runc {};
  sysboxMgrFs = pkgs.callPackage ../../../packages/sysbox-ce {};

  # ── containerd v3 config template ───────────────────────────────────────────
  #
  # k3s with containerd 2.x reads config-v3.toml.tmpl (not config.toml.tmpl).
  # The v3 config schema uses plugin namespace io.containerd.cri.v1.runtime
  # instead of the v2 io.containerd.grpc.v1.cri namespace.
  # {{ template "base" . }} expands the standard k3s containerd base config.
  # SystemdCgroup = false because sysbox manages cgroup delegation itself.
  #
  # sysbox-runc 0.7.0 implements the `features` subcommand, so containerd 2.x
  # reports user_namespaces: true for this handler. Pods with hostUsers: false
  # + runtimeClassName: sysbox-runc work correctly.
  #
  # References:
  #   https://docs.k3s.io/advanced#configuring-containerd
  #   https://docs.k3s.io/blog/2025/09/27/k3s-sysbox
  containerdConfigV3 = pkgs.writeText "config-v3.toml.tmpl" ''
    # Generated by nixos/modules/sysbox — DO NOT EDIT by hand.
    # containerd 2.x / k3s 1.32+ (v3 config schema)

    {{ template "base" . }}

    # ── Sysbox runtime ────────────────────────────────────────────────────────
    [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.sysbox-runc]
      runtime_type = "io.containerd.runc.v2"

    [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.sysbox-runc.options]
      BinaryName    = "${sysboxRunc}/bin/sysbox-runc"
      SystemdCgroup = false
  '';

  # ── sysctl settings required by sysbox ──────────────────────────────────────
  sysboxSysctls = {
    "kernel.unprivileged_userns_clone" = 1;
    "fs.inotify.max_queued_events"     = 1048576;
    "fs.inotify.max_user_watches"      = 1048576;
    "fs.inotify.max_user_instances"    = 1048576;
    "kernel.keys.maxkeys"              = 20000;
    "kernel.keys.maxbytes"             = 1400000;
    "kernel.pid_max"                   = 4194304;
  };
in
{
  options.services.coder-nixos.sysbox = {
    enable = lib.mkOption {
      type        = lib.types.bool;
      default     = false;
      description = ''
        Enable sysbox-runc as an additional OCI runtime on the k3s base.
        Workspace pods reference it via runtimeClassName: sysbox-runc and get
        unprivileged Docker-in-container support without privileged: true.
        Enables the base k3s server (nixos/modules/k3s).

        Do NOT enable services.coder-nixos.podman at the same time — both
        expect to own pod scheduling.
      '';
    };
  };

  config = lib.mkIf cfg.enable {

    # Pull in the base single-node k3s server.
    services.coder-nixos.k3s.enable = lib.mkDefault true;

    # ── Kernel parameters sysbox requires ─────────────────────────────────────
    # Per-key assignment so these merge with the base's user.max_user_namespaces.
    boot.kernel.sysctl  = sysboxSysctls;
    boot.kernelParams   = [ "user_namespace.enable=1" ];

    # ── subuid/subgid for kubelet user namespace allocation ───────────────────
    # k3s runs as root; kubelet needs a large subuid/subgid range to allocate
    # UID maps for pods using hostUsers: false (user namespaces).
    # 65536 UIDs per pod × up to 110 pods = ~7.2M UIDs needed.
    users.users.root = {
      subUidRanges = [{ startUid = 231072; count = 7208960; }];
      subGidRanges = [{ startGid = 231072; count = 7208960; }];
    };

    # containerdConfigTemplate = null means the NixOS k3s module will NOT write
    # config.toml.tmpl. We deploy config-v3.toml.tmpl via the
    # k3s-containerd-config service below (required for containerd 2.x).
    # mkForce because the base k3s module leaves this at the NixOS default.
    services.k3s.containerdConfigTemplate = lib.mkForce null;

    # ── Deploy containerd v3 config template before k3s starts ────────────────
    #
    # containerd 2.x (bundled with k3s 1.32+) uses config-v3.toml.tmpl. The NixOS
    # k3s module only writes config.toml.tmpl (v2 schema), which containerd 2.x
    # ignores — so we handle this ourselves: symlink config-v3.toml.tmpl into the
    # containerd config dir and remove the stale config.toml.tmpl if present.
    systemd.services.k3s-containerd-config = {
      description = "Deploy sysbox containerd v3 config template for k3s";
      wantedBy    = [ "k3s.service" ];
      before      = [ "k3s.service" ];
      after       = [ "sysbox.service" ];

      serviceConfig = {
        Type            = "oneshot";
        RemainAfterExit = true;
        ExecStart = pkgs.writeShellScript "k3s-containerd-config" ''
          set -euo pipefail
          DIR=/var/lib/rancher/k3s/agent/etc/containerd
          mkdir -p "$DIR"

          # Remove stale v2 template — containerd 2.x ignores it but its presence
          # alongside config-v3.toml.tmpl could cause confusion.
          rm -f "$DIR/config.toml.tmpl"

          # Symlink the v3 template from the Nix store.
          ln -sf ${containerdConfigV3} "$DIR/config-v3.toml.tmpl"

          echo "containerd v3 config template deployed: $DIR/config-v3.toml.tmpl -> ${containerdConfigV3}"
        '';
      };
    };

    # ── sysbox-mgr daemon ──────────────────────────────────────────────────────
    systemd.services.sysbox-mgr = {
      description = "sysbox-mgr (part of the Sysbox container runtime)";
      wantedBy    = [ "multi-user.target" ];
      before      = [ "k3s.service" ];
      after       = [ "network.target" ];

      startLimitIntervalSec = 0;  # unlimited restarts
      serviceConfig = {
        Type               = "notify";
        ExecStart          = "${sysboxMgrFs}/bin/sysbox-mgr";
        # sysbox calls iptables at runtime for netfilter setup
        ExecStartPre       = "+${pkgs.coreutils}/bin/mkdir -p /var/lib/sysbox /run/sysbox";
        Environment        = "PATH=${pkgs.iptables}/bin:${pkgs.kmod}/bin:/run/wrappers/bin:/run/current-system/sw/bin";
        TimeoutStartSec    = 45;
        TimeoutStopSec     = 90;
        NotifyAccess       = "main";
        OOMScoreAdjust     = -500;
        LimitNOFILE        = "infinity";
        LimitNPROC         = "infinity";
        Restart            = "on-failure";
        RestartSec         = "5s";
      };
    };

    # ── sysbox-fs daemon ────────────────────────────────────────────────────────
    systemd.services.sysbox-fs = {
      description = "sysbox-fs (part of the Sysbox container runtime)";
      wantedBy    = [ "multi-user.target" ];
      after       = [ "sysbox-mgr.service" ];
      before      = [ "k3s.service" ];

      startLimitIntervalSec = 0;  # unlimited restarts
      serviceConfig = {
        Type               = "notify";
        ExecStart          = "${sysboxMgrFs}/bin/sysbox-fs";
        # sysbox-fs uses FUSE for /proc and /sys mounts; needs fusermount in PATH
        Environment        = "PATH=${pkgs.fuse}/bin:${pkgs.fuse3}/bin:/run/wrappers/bin:/run/current-system/sw/bin";
        TimeoutStartSec    = 45;
        TimeoutStopSec     = 45;
        NotifyAccess       = "main";
        OOMScoreAdjust     = -500;
        LimitNOFILE        = "infinity";
        LimitNPROC         = "infinity";
        Restart            = "on-failure";
        RestartSec         = "5s";
      };
    };

    # ── sysbox umbrella target ──────────────────────────────────────────────────
    systemd.services.sysbox = {
      description = "Sysbox container runtime";
      wantedBy    = [ "multi-user.target" ];
      bindsTo     = [ "sysbox-mgr.service" "sysbox-fs.service" ];
      after       = [ "sysbox-mgr.service" "sysbox-fs.service" ];
      before      = [ "k3s.service" ];

      serviceConfig = {
        Type      = "exec";
        ExecStart = pkgs.writeShellScript "sysbox-check" ''
          ${sysboxRunc}/bin/sysbox-runc --version
          ${sysboxMgrFs}/bin/sysbox-mgr  --version
          ${sysboxMgrFs}/bin/sysbox-fs   --version
          exec ${pkgs.coreutils}/bin/sleep infinity
        '';
      };
    };

    # ── RuntimeClass auto-deploy manifest ───────────────────────────────────────
    # k3s auto-deploys YAML files placed in /var/lib/rancher/k3s/server/manifests/
    # The NixOS k3s module accepts an attrset of submodules with a `content` key.
    services.k3s.manifests."sysbox-runtimeclass".content = {
      apiVersion = "node.k8s.io/v1";
      kind       = "RuntimeClass";
      metadata.name = "sysbox-runc";
      handler    = "sysbox-runc";
    };

    # ── FUSE: allow non-root mounts (needed by sysbox-fs) ─────────────────────
    programs.fuse.userAllowOther = true;

    # ── Additional packages ───────────────────────────────────────────────────
    # rsync is required by the sysbox-mgr preflight check; without it,
    # sysbox-mgr exits immediately and pods stay stuck in ContainerCreating.
    environment.systemPackages = with pkgs; [ fuse fuse3 rsync ];
  };
}
