# k3s-sysbox.nix — NixOS module: k3s server + sysbox-runc runtime
#
# Add to configuration.nix imports, then set:
#   services.coder-nixos.k3s-sysbox.enable = true;
#
# NOTE: This module uses a DIFFERENT option than k3s-podman.nix to avoid
# conflicts.  Import only ONE of k3s-podman.nix / k3s-sysbox.nix.
#
# The coder user (UID 991) can read the kubeconfig at:
#   /etc/rancher/k3s/k3s.yaml   (mode 0640, group coder)
#
# Apply: sudo nixos-rebuild switch

{ config, lib, pkgs, ... }:

let
  cfg = config.services.coder-nixos.k3s-sysbox;

  # ── sysbox-runc 0.7.0 — built from source via pkgs/sysbox-runc.nix ──────
  #
  # sysbox-runc 0.7.0 adds the `features` subcommand required by containerd 2.x
  # to report user_namespaces: true in RuntimeFeatures, enabling hostUsers: false
  # in pod specs with runtimeClassName: sysbox-runc.
  #
  # See pkgs/sysbox-runc.nix for build details and update instructions.
  sysboxRunc = pkgs.callPackage ../pkgs/sysbox-runc.nix {};

  # ── Sysbox v0.6.7 CE — sysbox-mgr and sysbox-fs from .deb ───────────────
  #
  # 0.6.7 is the latest released .deb (May 2025). sysbox-runc is replaced by
  # the separately-built 0.7.0 binary above.
  #
  # nestybox publishes both linux_amd64 and linux_arm64 .debs; pick the one
  # matching the build platform. Update hashes with:
  #   nix store prefetch-file https://github.com/nestybox/sysbox/releases/download/v0.6.7/sysbox-ce_0.6.7.linux_<arch>.deb
  sysboxArch =
    {
      "x86_64-linux"  = "amd64";
      "aarch64-linux" = "arm64";
    }.${pkgs.stdenvNoCC.hostPlatform.system}
      or (throw "k3s-sysbox.nix: unsupported system ${pkgs.stdenvNoCC.hostPlatform.system}");

  sysboxDebHashes = {
    amd64 = "sha256-t6w4nloZWSyt8W4Mow5AkZUWEo9uG3+Z4ctP9kVUFy4=";
    arm64 = "sha256-FtgBI7pTBYz5D1poaG4pdiHql5QmAmguNLM1J4OQj5E=";
  };

  sysboxDeb = pkgs.fetchurl {
    url  = "https://github.com/nestybox/sysbox/releases/download/v0.6.7/sysbox-ce_0.6.7.linux_${sysboxArch}.deb";
    hash = sysboxDebHashes.${sysboxArch};
  };

  sysboxMgrFs = pkgs.stdenvNoCC.mkDerivation {
    pname   = "sysbox-ce";
    version = "0.6.7";

    src = sysboxDeb;

    nativeBuildInputs = [ pkgs.dpkg ];

    unpackPhase = ''
      dpkg-deb --extract $src unpacked
    '';

    installPhase = ''
      mkdir -p $out/bin
      install -m 0755 unpacked/usr/bin/sysbox-mgr  $out/bin/sysbox-mgr
      install -m 0755 unpacked/usr/bin/sysbox-fs   $out/bin/sysbox-fs
    '';

    # Binaries are statically linked — verified with readelf -d (no dynamic section).
    dontStrip        = true;
    dontAutoPatchelf = true;

    meta = {
      description = "Sysbox CE 0.6.7 — sysbox-mgr, sysbox-fs";
      homepage    = "https://github.com/nestybox/sysbox";
      license     = lib.licenses.asl20;
      platforms   = [ "x86_64-linux" "aarch64-linux" ];
    };
  };

  # ── containerd v3 config template ─────────────────────────────────────────
  #
  # k3s with containerd 2.x reads config-v3.toml.tmpl (not config.toml.tmpl).
  # The v3 config schema uses plugin namespace io.containerd.cri.v1.runtime
  # instead of the v2 io.containerd.grpc.v1.cri namespace.
  # {{ template "base" . }} expands the standard k3s containerd base config.
  # SystemdCgroup = false because sysbox manages cgroup delegation itself.
  #
  # sysbox-runc 0.7.0 implements the `features` subcommand, so containerd 2.x
  # will report user_namespaces: true for this handler. Pods with
  # hostUsers: false + runtimeClassName: sysbox-runc will work correctly.
  #
  # References:
  #   https://docs.k3s.io/advanced#configuring-containerd
  #   https://docs.k3s.io/blog/2025/09/27/k3s-sysbox
  containerdConfigV3 = pkgs.writeText "config-v3.toml.tmpl" ''
    # Generated by k3s-sysbox.nix — DO NOT EDIT by hand.
    # containerd 2.x / k3s 1.32+ (v3 config schema)

    {{ template "base" . }}

    # ── Sysbox runtime ────────────────────────────────────────────────────────
    [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.sysbox-runc]
      runtime_type = "io.containerd.runc.v2"

    [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.sysbox-runc.options]
      BinaryName    = "${sysboxRunc}/bin/sysbox-runc"
      SystemdCgroup = false
  '';

  # ── sysctl settings required by sysbox ───────────────────────────────────
  sysboxSysctls = {
    "kernel.unprivileged_userns_clone" = 1;
    "fs.inotify.max_queued_events"     = 1048576;
    "fs.inotify.max_user_watches"      = 1048576;
    "fs.inotify.max_user_instances"    = 1048576;
    "kernel.keys.maxkeys"              = 20000;
    "kernel.keys.maxbytes"             = 1400000;
    "kernel.pid_max"                   = 4194304;
  };

in
{
  # ── Option declaration ────────────────────────────────────────────────────
  # Uses k3s-sysbox (not k3s) to avoid conflict with k3s-podman.nix.
  # Import only ONE of these two modules.
  options.services.coder-nixos.k3s-sysbox = {
    enable = lib.mkOption {
      type        = lib.types.bool;
      default     = false;
      description = ''
        Enable k3s (single-node server mode) with sysbox-runc as an
        additional OCI runtime. Workspace pods reference it via
        runtimeClassName: sysbox-runc and get unprivileged Docker-in-
        container support without privileged: true.

        Do NOT import k3s-podman.nix at the same time — both modules
        define services.k3s which would conflict.
      '';
    };
  };

  # ── Implementation ────────────────────────────────────────────────────────
  config = lib.mkIf cfg.enable {

    # ── Kernel parameters sysbox requires ──────────────────────────────────
    boot.kernel.sysctl  = sysboxSysctls;
    boot.kernelParams   = [ "user_namespace.enable=1" ];

    # ── subuid/subgid for kubelet user namespace allocation ───────────────
    # k3s runs as root; kubelet needs a large subuid/subgid range to allocate
    # UID maps for pods using hostUsers: false (user namespaces).
    # 65536 UIDs per pod × up to 110 pods = ~7.2M UIDs needed.
    users.users.root = {
      subUidRanges = [{ startUid = 231072; count = 7208960; }];
      subGidRanges = [{ startGid = 231072; count = 7208960; }];
    };

    # ── k3s service ────────────────────────────────────────────────────────
    services.k3s = {
      enable = true;
      role   = "server";

      extraFlags = toString [
        "--write-kubeconfig-mode=0640"
        "--disable=traefik"
        "--disable=servicelb"
        "--kubelet-arg=cgroup-driver=systemd"
        "--tls-san=${config.networking.hostName}.local"
      ];

      # containerdConfigTemplate = null means the NixOS k3s module will NOT
      # write config.toml.tmpl. We instead deploy config-v3.toml.tmpl via
      # the k3s-containerd-config service below (required for containerd 2.x).
      containerdConfigTemplate = null;
    };

    # ── Deploy containerd v3 config template before k3s starts ────────────
    #
    # containerd 2.x (bundled with k3s 1.32+) uses config-v3.toml.tmpl.
    # The NixOS k3s module only writes config.toml.tmpl (v2 schema), which
    # containerd 2.x ignores — so we handle this ourselves.
    #
    # We symlink config-v3.toml.tmpl into the containerd config dir and
    # remove the stale config.toml.tmpl if present.
    systemd.services.k3s-containerd-config = {
      description = "Deploy sysbox containerd v3 config template for k3s";
      wantedBy    = [ "k3s.service" ];
      before      = [ "k3s.service" ];
      after       = [ "sysbox.service" ];

      serviceConfig = {
        Type            = "oneshot";
        RemainAfterExit = true;
        ExecStart = pkgs.writeShellScript "k3s-containerd-config" ''
          set -euo pipefail
          DIR=/var/lib/rancher/k3s/agent/etc/containerd
          mkdir -p "$DIR"

          # Remove stale v2 template — containerd 2.x ignores it but its
          # presence alongside config-v3.toml.tmpl could cause confusion.
          rm -f "$DIR/config.toml.tmpl"

          # Symlink the v3 template from the Nix store.
          ln -sf ${containerdConfigV3} "$DIR/config-v3.toml.tmpl"

          echo "containerd v3 config template deployed: $DIR/config-v3.toml.tmpl -> ${containerdConfigV3}"
        '';
      };
    };

    # ── kubeconfig ownership fix + API readiness wait ────────────────────
    # Two ExecStartPost scripts run in order:
    #   1. k3s-fix-kubeconfig  — waits for k3s.yaml and fixes ownership
    #   2. k3s-wait-api-ready  — polls /readyz until the API accepts requests,
    #      so local-path-provisioner and other in-cluster pods don't enter
    #      CrashLoopBackOff before the API is up on cold boots.
    systemd.services.k3s.serviceConfig.ExecStartPost = lib.mkAfter [
      (pkgs.writeShellScript "k3s-fix-kubeconfig" ''
        for i in $(seq 1 30); do
          [ -f /etc/rancher/k3s/k3s.yaml ] && break
          sleep 1
        done
        chown root:coder /etc/rancher/k3s/k3s.yaml 2>/dev/null || true
        chmod 0640       /etc/rancher/k3s/k3s.yaml 2>/dev/null || true
      '')
      (pkgs.writeShellScript "k3s-wait-api-ready" ''
        echo "k3s-wait-api-ready: waiting for API server /readyz..."
        for i in $(seq 1 120); do
          if ${pkgs.curl}/bin/curl -sf -o /dev/null \
              --cacert /var/lib/rancher/k3s/server/tls/server-ca.crt \
              https://127.0.0.1:6443/readyz 2>/dev/null; then
            echo "k3s-wait-api-ready: API ready after ''${i}s"
            exit 0
          fi
          sleep 1
        done
        echo "k3s-wait-api-ready: timed out after 120s — continuing anyway"
        exit 0
      '')
    ];

    # ── sysbox-mgr daemon ──────────────────────────────────────────────────
    systemd.services.sysbox-mgr = {
      description = "sysbox-mgr (part of the Sysbox container runtime)";
      wantedBy    = [ "multi-user.target" ];
      before      = [ "k3s.service" ];
      after       = [ "network.target" ];

      startLimitIntervalSec = 0;  # unlimited restarts
      serviceConfig = {
        Type               = "notify";
        ExecStart          = "${sysboxMgrFs}/bin/sysbox-mgr";
        # sysbox calls iptables at runtime for netfilter setup
        ExecStartPre       = "+${pkgs.coreutils}/bin/mkdir -p /var/lib/sysbox /run/sysbox";
        Environment        = "PATH=${pkgs.iptables}/bin:${pkgs.kmod}/bin:/run/wrappers/bin:/run/current-system/sw/bin";
        TimeoutStartSec    = 45;
        TimeoutStopSec     = 90;
        NotifyAccess       = "main";
        OOMScoreAdjust     = -500;
        LimitNOFILE        = "infinity";
        LimitNPROC         = "infinity";
        Restart            = "on-failure";
        RestartSec         = "5s";
      };
    };

    # ── sysbox-fs daemon ───────────────────────────────────────────────────
    systemd.services.sysbox-fs = {
      description = "sysbox-fs (part of the Sysbox container runtime)";
      wantedBy    = [ "multi-user.target" ];
      after       = [ "sysbox-mgr.service" ];
      before      = [ "k3s.service" ];

      startLimitIntervalSec = 0;  # unlimited restarts
      serviceConfig = {
        Type               = "notify";
        ExecStart          = "${sysboxMgrFs}/bin/sysbox-fs";
        # sysbox-fs uses FUSE for /proc and /sys mounts; needs fusermount in PATH
        Environment        = "PATH=${pkgs.fuse}/bin:${pkgs.fuse3}/bin:/run/wrappers/bin:/run/current-system/sw/bin";
        TimeoutStartSec    = 45;
        TimeoutStopSec     = 45;
        NotifyAccess       = "main";
        OOMScoreAdjust     = -500;
        LimitNOFILE        = "infinity";
        LimitNPROC         = "infinity";
        Restart            = "on-failure";
        RestartSec         = "5s";
      };
    };

    # ── sysbox umbrella target ─────────────────────────────────────────────
    systemd.services.sysbox = {
      description = "Sysbox container runtime";
      wantedBy    = [ "multi-user.target" ];
      bindsTo     = [ "sysbox-mgr.service" "sysbox-fs.service" ];
      after       = [ "sysbox-mgr.service" "sysbox-fs.service" ];
      before      = [ "k3s.service" ];

      serviceConfig = {
        Type      = "exec";
        ExecStart = pkgs.writeShellScript "sysbox-check" ''
          ${sysboxRunc}/bin/sysbox-runc --version
          ${sysboxMgrFs}/bin/sysbox-mgr  --version
          ${sysboxMgrFs}/bin/sysbox-fs   --version
          exec ${pkgs.coreutils}/bin/sleep infinity
        '';
      };
    };

    # ── RuntimeClass auto-deploy manifest ─────────────────────────────────
    # k3s auto-deploys YAML files placed in /var/lib/rancher/k3s/server/manifests/
    # The NixOS k3s module accepts an attrset of submodules with a `content` key.
    services.k3s.manifests."sysbox-runtimeclass".content = {
      apiVersion = "node.k8s.io/v1";
      kind       = "RuntimeClass";
      metadata.name = "sysbox-runc";
      handler    = "sysbox-runc";
    };

    # ── Pre-create the coder-workspaces namespace ────────────────────────────
    # Templates deploy workloads into this namespace; they should not own it.
    systemd.services.coder-k3s-namespace = {
      description = "Create coder-workspaces namespace in k3s";
      wantedBy    = [ "multi-user.target" ];
      after       = [ "k3s.service" ];
      requires    = [ "k3s.service" ];

      serviceConfig = {
        Type            = "oneshot";
        RemainAfterExit = true;
        ExecStart = pkgs.writeShellScript "coder-k3s-namespace" ''
          set -euo pipefail
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          for i in $(seq 1 30); do
            [ -f "$KUBECONFIG" ] && break
            sleep 1
          done
          ${pkgs.kubectl}/bin/kubectl create namespace coder-workspaces \
            --dry-run=client -o yaml \
            | ${pkgs.kubectl}/bin/kubectl apply -f -
          echo "coder-workspaces namespace ready"
        '';
      };
    };

    # ── KUBECONFIG system-wide ────────────────────────────────────────────
    environment.variables.KUBECONFIG = "/etc/rancher/k3s/k3s.yaml";

    # ── Inject KUBECONFIG into coder.service ─────────────────────────────
    # Inject KUBECONFIG for Terraform's kubernetes provider, and order after
    # coder-k3s-namespace so the coder-workspaces namespace exists before
    # Coder's first workspace build (else it fails: namespace not found).
    #
    # NOTE: use `wants` (soft), NOT `requires` (hard), for the namespace dep.
    # With `after` + `requires`, a failed coder-k3s-namespace.service (which
    # runs `set -euo pipefail` and can flake on a cold first boot if the k3s
    # API isn't accepting requests yet) would prevent coder.service from
    # starting at all. We only want ordering here; the namespace service is
    # already `wantedBy = multi-user.target`, so `wants` keeps it pulled in and
    # ordered before coder without letting a transient flake block the server.
    systemd.services.coder = {
      after = [ "coder-k3s-namespace.service" ];
      wants = [ "coder-k3s-namespace.service" ];
      environment = {
        KUBECONFIG = "/etc/rancher/k3s/k3s.yaml";
      };
    };

    # ── Ensure coder group exists ─────────────────────────────────────────
    users.groups.coder = lib.mkDefault {};

    # ── Additional packages ───────────────────────────────────────────────
    # rsync is required by sysbox-mgr preflight check; without it,
    # sysbox-mgr exits immediately and pods stay stuck in ContainerCreating.
    environment.systemPackages = with pkgs; [ kubectl kubernetes-helm fuse fuse3 rsync ];

    # ── FUSE: allow non-root mounts (needed by sysbox-fs) ─────────────────
    programs.fuse.userAllowOther = true;

    # ── Firewall ──────────────────────────────────────────────────────────
    networking.firewall.allowedTCPPorts = lib.mkIf config.networking.firewall.enable [ 6443 ];

  }; # end config
}
